#!/usr/bin/env -S node

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import {
  buildFolderPromptGlob,
  buildRecursivePromptGlob,
  loadRepositoryConfig,
  resolveConfiguredPath,
  toPosixPath,
  type RepositoryConfig,
} from "./lib/config.ts";

/**
 * CLI configuration for documentation generation.
 */
interface BuildDocumentationOptions {
  readonly rootDir: string;
  readonly readmePath: string;
  readonly promptsRoot: string;
  readonly verbose: boolean;
  readonly config: RepositoryConfig;
}

/**
 * Minimal directory entry used for generated documentation.
 */
interface PromptFolder {
  readonly name: string;
  readonly relativePath: string;
}

/**
 * Main entry point.
 *
 * @returns Promise that resolves when documentation has been generated.
 */
async function main(): Promise<void> {
  try {
    const options = await parseArgs(process.argv.slice(2));
    await updateReadmePromptSettingsSection(options);
  } catch (error: unknown) {
    console.error(`[build-documentation] ${getErrorMessage(error)}`);
    process.exit(1);
  }
}

/**
 * Parse CLI arguments.
 *
 * @param argv CLI arguments after script name.
 * @returns Parsed options.
 */
async function parseArgs(
  argv: readonly string[],
): Promise<BuildDocumentationOptions> {
  if (argv.includes("--help") || argv.includes("-h")) {
    printHelp();
    process.exit(0);
  }

  const rootDir = process.cwd();
  const config = await loadRepositoryConfig(rootDir);

  return {
    rootDir,
    readmePath: resolveConfiguredPath(rootDir, config.paths.readme),
    promptsRoot: resolveConfiguredPath(rootDir, config.paths.promptFilesRoot),
    verbose: argv.includes("--verbose"),
    config,
  };
}

/**
 * Print help output.
 */
function printHelp(): void {
  const scriptName = path.basename(
    process.argv[1] ?? "build-documentation.ts",
  );

  console.log(`Usage: node ./scripts/${scriptName} [options]

Options:
  --verbose   Show additional diagnostics
  --help, -h  Show this help

Behaviour:
  Updates the generated prompt files settings section in README.md.

Configuration:
  Reads paths and setting names from config.toml.
`);
}

/**
 * Update the generated prompt settings section in README.md.
 *
 * @param options Build documentation options.
 */
async function updateReadmePromptSettingsSection(
  options: BuildDocumentationOptions,
): Promise<void> {
  const readme = await fs.readFile(options.readmePath, "utf8");
  const promptFolders = await listPromptFolders(options);

  const replacement = buildGeneratedSection(options.config, promptFolders);
  const updated = replaceMarkedSection(readme, replacement, options.config);

  await fs.writeFile(options.readmePath, updated, "utf8");

  if (options.verbose) {
    console.log(`[ok] Updated ${path.relative(options.rootDir, options.readmePath)}`);
    console.log(`[ok] Found ${promptFolders.length} prompt folder(s)`);
  }
}

/**
 * List direct prompt folders under the configured prompt files root.
 *
 * @param options Build documentation options.
 * @returns Sorted prompt folder list.
 */
async function listPromptFolders(
  options: BuildDocumentationOptions,
): Promise<PromptFolder[]> {
  try {
    const entries = await fs.readdir(options.promptsRoot, {
      withFileTypes: true,
    });

    return entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const absolutePath = path.join(options.promptsRoot, entry.name);

        return {
          name: entry.name,
          relativePath: toPosixPath(path.relative(options.rootDir, absolutePath)),
        };
      })
      .sort((left, right) => left.relativePath.localeCompare(right.relativePath));
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return [];
    }

    throw error;
  }
}

/**
 * Build the generated README section.
 *
 * @param config Repository config.
 * @param promptFolders Prompt folders found under the configured prompt root.
 * @returns Markdown content to place between the markers.
 */
function buildGeneratedSection(
  config: RepositoryConfig,
  promptFolders: readonly PromptFolder[],
): string {
  const startMarker = config.readme.promptFilesSettings.startMarker;
  const endMarker = config.readme.promptFilesSettings.endMarker;
  const settingKey = config.prompts.settingKey;
  const recursiveGlob = buildRecursivePromptGlob(config);

  const folderEntries = buildFolderEntries(config, promptFolders);
  const folderList = buildFolderList(promptFolders);

  return `${startMarker}
<!-- This section is generated by \`npm run build:documentation\`. Do not edit manually. -->

## VS Code prompt file recommendations

VS Code can load prompt files from configured workspace locations. This repository keeps generated prompt files under \`${config.paths.promptFilesRoot}/\`.

There are two useful configuration styles.

### Option 1: one recursive glob

Use this when all prompt recommendations should be available at once and new folders should be picked up automatically.

\`\`\`jsonc
{
  "${settingKey}": {
    "${recursiveGlob}": true
  }
}
\`\`\`

### Option 2: individual folder entries

Use this when prompt recommendation groups should be enabled or disabled independently.

\`\`\`jsonc
{
  "${settingKey}": {
${folderEntries}
  }
}
\`\`\`

Current prompt folders covered by the individual-folder example:

${folderList}

${endMarker}`;
}

/**
 * Build JSONC lines for the individual folder configuration sample.
 *
 * @param config Repository config.
 * @param promptFolders Prompt folders.
 * @returns JSONC object entries.
 */
function buildFolderEntries(
  config: RepositoryConfig,
  promptFolders: readonly PromptFolder[],
): string {
  if (promptFolders.length === 0) {
    const fallback = buildFolderPromptGlob(
      config,
      path.posix.join(config.paths.promptFilesRoot, "example"),
    );

    return `    "${fallback}": true`;
  }

  return promptFolders
    .map((folder, index) => {
      const suffix = index === promptFolders.length - 1 ? "" : ",";
      const folderGlob = buildFolderPromptGlob(config, folder.relativePath);

      return `    "${folderGlob}": true${suffix}`;
    })
    .join("\n");
}

/**
 * Build a Markdown list of prompt folders.
 *
 * @param promptFolders Prompt folders.
 * @returns Markdown list.
 */
function buildFolderList(promptFolders: readonly PromptFolder[]): string {
  if (promptFolders.length === 0) {
    return `- No direct prompt folders were found.`;
  }

  return promptFolders
    .map((folder) => `- \`${folder.relativePath}/\``)
    .join("\n");
}

/**
 * Replace a marked section in a Markdown file.
 *
 * @param content Original Markdown content.
 * @param replacement Full replacement content, including markers.
 * @param config Repository config.
 * @returns Updated Markdown content.
 */
function replaceMarkedSection(
  content: string,
  replacement: string,
  config: RepositoryConfig,
): string {
  const startMarker = config.readme.promptFilesSettings.startMarker;
  const endMarker = config.readme.promptFilesSettings.endMarker;

  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `README.md must contain ${startMarker} and ${endMarker} markers.`,
    );
  }

  const before = content.slice(0, startIndex).trimEnd();
  const after = content.slice(endIndex + endMarker.length).trimStart();

  return `${before}\n\n${replacement}\n\n${after}`;
}

/**
 * Check whether a value is a Node.js error with a code.
 *
 * @param value Unknown error value.
 * @returns True when the value has a string code.
 */
function isNodeError(value: unknown): value is NodeJS.ErrnoException {
  return value instanceof Error && "code" in value;
}

/**
 * Convert an unknown error into a printable message.
 *
 * @param error Unknown error value.
 * @returns Error message.
 */
function getErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
}

await main();
